### ISSUE TITLE
No imports

### ISSUE THREAD

**Issue by mailwl** [SocraticBliss/ps4_module_loader#1]
Can you add Imports for loaded ELF, like [belf](https://github.com/balika011/belf) did?
![image](https://user-images.githubusercontent.com/629437/65835508-bef06f00-e2ef-11e9-8cc6-d8ecffdaf491.png)

**Comment by SocraticBliss** [comment]
Well, I do have it in there, but it requires a customized IDA Python build... I'll see how I can manage it...
