### ISSUE TITLE
Rename class Symbol to something other (ElfSymbol?)

### ISSUE THREAD

**Issue by mailwl** [SocraticBliss/ps4_module_loader#62]
on one of my computers ps4_module_loader don't show names of functions. The reason - Symbol class constructor needs 6 parameters, but only 2 provided. Looks like some other library uses same name.
I'm totally don't know Python, and have no idea how it happens, but may you rename the class to more unique name?

**Comment by SocraticBliss** [comment]
Have you tried renaming it and seeing if it solves your issue?

**Comment by mailwl** [comment]
yes, it solved by rename the Symbol class. it happens only on my work PC, which used for many experiments, included install a lot of python libs not related with IDA. on my home pc it works on clean python environment without any issues
