### ISSUE TITLE
Pseudocode Wont Open

### ISSUE THREAD

**Issue by avze** [SocraticBliss/ps4_module_loader#72]
After I have decompiled my default_mp.elf and saved it as an .i64, I try to reopen in IDA, and when i try to load Pseudocode it says "please use ida (not ida64) to decompile the current file"

**Comment by SocraticBliss** [comment]
This isn't a problem with the loader. As the processor that I specify is the "metapc" and the pointer size that I utilize are CM_N64.

This is most likely an issue with IDA/hexrays itself.

**Comment by thalheimbenjamin-blip** [comment]
you could remove this comment idc.set_inf_attr(INF_LFLAGS, LFLG_64BIT) in line 183 and then it works
