### ISSUE TITLE
cant load minecraft ps4 edition 

### ISSUE THREAD

**Issue by LiEnby** [SocraticBliss/ps4_module_loader#74]
i can load the Minecraft.Client.elf (LCE) executable, but not the main eboot.bin (bedrock) executable 
![image](https://github.com/user-attachments/assets/0d3887ea-99a0-45dc-a580-9fc3303ee15c)

**Comment by LiEnby** [comment]
i have the eboot.elf but its too darn big to upload here. uh

**Comment by SocraticBliss** [comment]
Seems like it has (empty) section headers, to bypass this message (and load the file), just modify the ELF header of the file itself and say that there are no section headers present...

For example, if you open the eboot.bin/elf in a hex editor, go to byte(s) 0x30 and 0x31 and set these values to 0. Then it should (hopefully) get past this.
