### ISSUE TITLE
Wrong constant

### ISSUE THREAD

**Issue by mailwl** [SocraticBliss/ps4_module_loader#77]
https://github.com/SocraticBliss/ps4_module_loader/blob/41a8b583701dd6e03b8e333ee2bd6b3ed6a3db31/ps4_module.py#L430

Probably never meets, but in code:

```
0x2  : 'WEAK_EXPORT',
0x8  : 'LOOSE_IMPORT',
0x10 : 'WEAK_EXPORT|LOOSE_IMPORT',
```

`WEAK_EXPORT|LOOSE_IMPORT == 0xA`, not 0x10?

**Comment by SocraticBliss** [comment]
Fair point! Good catch :)
